Added spending logs for 2022-Q1 and 2022-Q2
grincc/finance pull request #12
Opened 2022-09-15 09:51 UTC by cekickafa

There is a missing description for transaction with spend_id:8 at 2022-02-27 1738$.

2022-12-01 19:06 UTC, MCM-Mike approved these changes
I did check a few transaction by hand and they match. 
Therefore I can approve it.

2022-12-01 19:10 UTC, cekickafa commented
> I did check a few transaction by hand and they match. Therefore I can approve it.
Thanks for review.

2022-12-05 23:08 UTC, future3OOO requested changes

2022-12-05 23:08 UTC, future3OOO commented on pending-payments.md
> +|@dtavarez|Aug-December funding request|3.750 €|11.22.2022|**86.855 GRIN**|0.4317|Yes|**Pending** |
| 3750 €| 86,855.115 GRIN | Paid 11/24

2022-12-06 10:13 UTC, cekickafa commented on pending-payments.md
> +|@dtavarez|Aug-December funding request|3.750 €|11.22.2022|**86.855 GRIN**|0.4317|Yes|**Pending** |
@future3OOO edited as '**Paid**'

2022-12-22 15:19 UTC, Anynomouss approved these changes
I found no problems with the report, but I would propose to simplify by making it yearly, not quarterly. Instead of reporting changes in balance per quarter, we can provide a graph of changes in value hold in BTC and USD using this handy website. I removes all the manual labor of calculating changes in Grin and BTC for a certain period:
https://bitinfocharts.com/bitcoin/address/bc1qmdhmgmhd6j89225hzdh7dxqgmen3y2q0g4vgpez0tw9tkp4ae39qsqvuyl

For the reporting I recommend changing from reporting per quarter to just yearly. Show all incoming and outgoing, or begin value at the year 2022 and end value at the end of 2022, since there are many fluctuation with incoming miner payments etc. Only mention donations that came in separately as total amount of  received donations in 2022 for Grin.  In other words, keep it as simple as possible, just a table with a small summary and separate mention of donations.

2022-12-22 16:00 UTC, cekickafa commented
I will summarize it for 2022. 

> I found no problems with the report, but I would propose to simplify by making it yearly, not quarterly. Instead of reporting changes in balance per quarter, we can provide a graph of changes in value hold in BTC and USD using this handy website. I removes all the manual labor of calculating changes in Grin and BTC for a certain period: https://bitinfocharts.com/bitcoin/address/bc1qmdhmgmhd6j89225hzdh7dxqgmen3y2q0g4vgpez0tw9tkp4ae39qsqvuyl
> 
> For the reporting I recommend changing from reporting per quarter to just yearly. Show all incoming and outgoing, or begin value at the year 2022 and end value at the end of 2022, since there are many fluctuation with incoming miner payments etc. Only mention donations that came in separately as total amount of received donations in 2022 for Grin. In other words, keep it as simple as possible, just a table with a small summary and separate mention of donations.

I will summarize as 2022 and simplfy it.

2023-02-02 09:35 UTC, Anynomouss approved these changes

2023-03-26 14:33 UTC, mojitoo approved these changes

2023-03-26 16:49 UTC, davidtavarez approved these changes

2023-03-26 16:50 UTC, merged